apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hellocloud-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hellocloud-ip
  labels:
    app: hellocloud
spec:
  backend:
    serviceName: hellocloud
    servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hellocloud
  labels:
    app: hellocloud
spec:
  type: NodePort
  selector:
    app: hellocloud
    tier: web
  ports:
  - port: 80
    targetPort: 8080