apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hellocloud
  name: hellocloud
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hellocloud
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hellocloud
    spec:
      containers:
      - name: hellocloud
        args:
        - npm
        - run
        - start
        image: gcr.io/dirthub/hellocloud:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: hellocloud
        - secretRef:
            name: hellocloud
        ports:
        - containerPort: 8081
          protocol: TCP
        imagePullPolicy: IfNotPresent
        