steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/flipthetable/hellocloud", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/flipthetable/hellocloud"]
  - name: "gcr.io/cloud-builders/gke-deploy:stable"
    args:
      - run
      - --filename=deploy/manifests/hellocloud.yaml
      - --image=gcr.io/flipthetable/hellocloud:latest
      - --location=us-west2
      - --cluster=default-cluster
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - apply
      - -f
      - deploy/manifests/hellocloud-service.yaml
images: ["gcr.io/flipthetable/hellocloud"]
